apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    version: v6.3.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
      version: v6.3.0
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
        version: v6.3.0
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: kibana
        effect: NoSchedule
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana:6.3.2
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1500m
            memory: 2500Mi
          requests:
            cpu: 500m
            memory: 2000Mi
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
          - name: SERVER_BASEPATH
            value: /api/v1/proxy/namespaces/kube-system/services/kibana-logging
          # - name: XPACK_MONITORING_ENABLED
          #   value: "false"
          # - name: XPACK_SECURITY_ENABLED
          #   value: "false"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP